SensorDataChallenge/Controllers/ApplicationUsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SensorDataChallenge.DTOs;
using SensorDataChallenge.Enums;
using SensorDataChallenge.Filters;
using SensorDataChallenge.Interfaces;
using System;
using System.Threading.Tasks;

namespace SensorDataChallenge.Controllers
{
    public class ApplicationUsersController : Controller
    {
        private readonly IApplicationUserService _applicationUserService;
        public ApplicationUsersController(IApplicationUserService applicationUserService)
        {
            _applicationUserService = applicationUserService;
        }

        // GET: ApplicationUsers
        [Authorize(PermissionEnum.ViewUsers)]
        public async Task<IActionResult> Index()
        {
            var usersDto = await _applicationUserService.GetAllUsers();
            return View(usersDto);
        }

        // GET: ApplicationUsers/Details/5
        [Authorize(PermissionEnum.ViewUsers)]
        public async Task<IActionResult> Details(string id)
        {
            var user = await _applicationUserService.GetUserById(id);
            if (user == null)
            {
                return NotFound();
            }
            var userDto = _applicationUserService.EntityToEntityPublicViewDTO(user);
            return View(userDto);
        }

        // GET: ApplicationUsers/Edit/5
        [Authorize(PermissionEnum.UpdateUser)]
        public async Task<IActionResult> Edit(string id)
        {
            var user = await _applicationUserService.GetUserById(id);
            var registerDto = _applicationUserService.EntityToRegisterDTO(user);
            var permissions = await _applicationUserService.GetPermissions();
            ViewBag.Permissions = new MultiSelectList(permissions, "Id", "Description"); var clients = _applicationUserService.GetClients();
            ViewData["ClientId"] = new SelectList(clients, "Id", "BusinessName");

            return View(registerDto);
        }

        // POST: ApplicationUsers/Edit/5
        [Authorize(PermissionEnum.UpdateUser)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, RegisterDTO registerDto)
        {
            registerDto.Permission = await _applicationUserService.Permissions(registerDto);

            if (id != registerDto.Id)
            {
                return NotFound();
            }

            try
            {
                await _applicationUserService.UpdateClient(id, registerDto);
            }
            catch (DbUpdateConcurrencyException ex)
            {

                return BadRequest(ex.Message);
            }
            return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "Index", _applicationUserService.GetAllUsers()) });

            //return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", registerDto) });
        }

        // POST: ApplicationUsers/Delete/5
        [Authorize(PermissionEnum.DeleteUser)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _applicationUserService.GetUserById(id);
            if (user == null)
            {
                return NotFound();
            }

            try
            {
                await _applicationUserService.DeleteAndSave(id);
                return Json(new { html = Helper.RenderRazorViewToString(this, "Index", _applicationUserService.GetAllUsers()) });
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

SensorDataChallenge/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SensorDataChallenge.DTOs;
using SensorDataChallenge.Enums;
using SensorDataChallenge.Filters;
using SensorDataChallenge.Interfaces;
using System.Threading.Tasks;
using static SensorDataChallenge.Helper;

namespace SensorDataChallenge.Controllers
{
    public class ClientsController : Controller
    {
        private readonly IClientService _clientService;

        public ClientsController(IClientService clientService)
        {
            _clientService = clientService;
        }

        // GET: Clients
        [Authorize(PermissionEnum.ViewClients)]
        public async Task<IActionResult> Index()
        {
            var clientsDto = await _clientService.GetAllClients();
            return View(clientsDto);
        }

        // GET: Clients/Details/5
        [Authorize(PermissionEnum.ViewClients)]
        public async Task<IActionResult> Details(int id)
        {
            var client = await _clientService.GetClientById(id);
            if (client == null)
            {
                return NotFound();
            }
            var clientDto = _clientService.EntityToEntityDTO(client);
            return View(clientDto);
        }

        // GET: Clients/Create
        [Authorize(PermissionEnum.CreateClient)]
        public IActionResult Create()
        {
            return View(new ClientDTO());
        }

        // POST: Clients/Create
        [Authorize(PermissionEnum.CreateClient)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClientDTO clientDto)
        {
            if (ModelState.IsValid)
            {
                var client = _clientService.EntityDTOToEntity(clientDto);
                var clientExist = await _clientService.ClientExist(client);
                if (clientExist)
                {
                    return Conflict($"El cliente {clientDto.BusinessName} ya existe.");
                }

                try
                {
                    await _clientService.AddAndSave(client);
                }
                catch (DbUpdateException ex)
                {
                    return BadRequest(ex.Message);
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", _clientService.GetAllClients()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", clientDto) });

        }

        // GET: Clients/Edit/5
        [Authorize(PermissionEnum.UpdateClient)]
        [NoDirectAccess]
        public async Task<IActionResult> Edit(int id)
        {
            var client = await _clientService.GetClientById(id);
            var clientDto = _clientService.EntityToEntityDTO(client);
            return View(clientDto);
        }

        // POST: Clients/5
        [Authorize(PermissionEnum.UpdateClient)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ClientDTO clientDto)
        {
            if (id != clientDto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var currentClient = await _clientService.GetClientById(id);
                    var client = _clientService.EntityDTOToEntity(clientDto);
                    client.IsActive = true;
                    await _clientService.UpdateAndSave(client);
                }
                catch (DbUpdateConcurrencyException ex)
                {

                    return BadRequest(ex.Message);
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", _clientService.GetAllClients()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", clientDto) });
        }

        // POST: ApplicationUsers/Delete/5
        [Authorize(PermissionEnum.DeleteClient)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _clientService.SoftDeleteAndSave(id);
                return Json(new { html = Helper.RenderRazorViewToString(this, "_ViewAll", _clientService.GetAllClients()) });
            }
            catch (DbUpdateConcurrencyException ex)
            {

                return BadRequest(ex.Message);
            }
        }
    }
}

SensorDataChallenge/Controllers/OpenLayerController.cs
using Microsoft.AspNetCore.Mvc;
using SensorDataChallenge.Enums;
using SensorDataChallenge.Filters;

namespace SensorDataChallenge.Controllers
{
    [Authorize(PermissionEnum.ViewMap)]
    public class OpenLayerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SensorDataChallenge/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SensorDataChallenge</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!-- ================== BEGIN core-css ================== -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <link href="~/css/default/app.min.css" rel="stylesheet" />

    @RenderSection("Styles", required: false)
    <!-- ================== END core-css ================== -->

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SensorDataChallenge</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Clients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationUsers" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OpenLayer" asp-action="Index">OpenLayerMap</a>
                        </li>
                    </ul>
                </div>
                <ul class="navbar-nav ml-auto">
                    @*If the user is signed-in display Logout link*@
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <form method="post" asp-controller="account" asp-action="Logout">
                                <button type="submit" style="width:auto" class="nav-link btn btn-link py-0">
                                    @User.Identity.Name Logout
                                </button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">
                                Login
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="modal" tabindex="-1" role="dialog" id="form-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>

    <div class="loaderbody" id="loaderbody">
        <div class="loader"></div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SensorDataChallenge - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/notify.min.js" asp-append-version="true"></script>

    <!-- ================== BEGIN core-js ================== -->
    <script src="~/js/app.min.js"></script>
    <script src="~/js/theme/default.min.js"></script>
    <!-- ================== END core-js ================== -->

    @RenderSection("Scripts", required: false)
</body>
</html>

SensorDataChallenge/Views/Shared/_ViewAll.cshtml
@model IEnumerable<SensorDataChallenge.DTOs.ClientDTO>

<p>
    <a onclick="showInPopup('@Url.Action("Create","Clients", null, Context.Request.Scheme)','New Client')" class="btn btn-success text-white font-weight-bold">New Client</a>
</p>
<table class="table text-center">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BusinessName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BusinessName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <a onclick="showInPopup('@Url.Action("Edit","Clients", new { id = item.Id }, Context.Request.Scheme)','Edit Client')" class="btn btn-primary">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                        </svg>
                    </a>
                    <form asp-action="Delete" asp-route-id="@item.Id" onsubmit="return jQueryAjaxDelete(this);" class="d-inline">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                    </form>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-secondary">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-eye-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                            <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z" />
                        </svg>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>